# -----------------------------------------------------------------
# Configuration file for http://travis-ci.org/#!/karmi/tire-contrib
# -----------------------------------------------------------------

language: ruby

rvm:
  - 1.8.7
  - 1.9.3
  - 2.0.0
  - jruby-19mode

script: "bundle exec rake test"

services:
  - elasticsearch

notifications:
  disable: true
